export const channels = {
  getAppUpdateState: "app:get-update-state",
  checkAppUpdate: "app:check-update",
  downloadAppUpdate: "app:download-update",
  installAppUpdate: "app:install-update",
  scanMemories: "memory:scan",
  startMemoryProfileGeneration: "memory:start-profile-generation",
  getMemoryProfileGeneration: "memory:get-profile-generation",
  cancelMemoryProfileGeneration: "memory:cancel-profile-generation",
  loadAgentMemorySnapshot: "memory:load-agent-snapshot",
  getSourceExcerpt: "memory:get-source-excerpt",
  draftCorrection: "memory:draft-correction",
  draftCorrectionFromContent: "memory:draft-correction-from-content",
  draftRevert: "memory:draft-revert",
  writeCorrection: "memory:write-correction",
  loadSkillInventory: "skills:load",
  loadSkillUsage: "skills:load-usage",
  saveSkillManifest: "skills:save-manifest",
  loadAgentConfigInventory: "agent-config:load",
  saveAgentProviderProfile: "agent-config:save",
  deleteAgentProviderProfile: "agent-config:delete",
  activateAgentProviderProfile: "agent-config:activate",
  loadMcpInventory: "mcp:load",
  revealSource: "shell:reveal-source",
} as const;
